### ISSUE TITLE
Bug: Overlapping Mount HP and Hunger Bar

### ISSUE THREAD

**Issue by SirAron111** [Tfarcenim/ClassicBar#12]
Riding a Horse or any tamed mob/ even untamed mobs that just pcik you up (counts as riding them ie ice and fire dragons/ erebus scorpiouns etc) well anyway the Bar for the mounts hp is overlapping with the hunger bar. (I think the mount hp bar should be placed vertically to the left middle side of the screen so it’s out of the way but still provides visual information instead of trying to stack even more pars on top of each other (would also a fitting place for the wing bar for botania flight)) but atm its just overlapping with hunger the bar.
![2019-04-06_17 50 27](https://user-images.githubusercontent.com/39855956/55671904-2378c700-5895-11e9-9646-81ae018fe110.png)
With all the Bug reports I make you must hate me at some point Xd

**Comment by Tfarcenim** [comment]
in vanilla the hunger bar doesn't display at all when riding a mount, time to fix.

**Comment by Tfarcenim** [comment]
0.1.11 should fix it.

**Comment by SirAron111** [comment]
mm ok the bar under the other one is gone now but the icons on the side and the numbers from the hunger bar are still present under the numbers on the horse hp bar same as picture above in version 0.1.11

**Comment by Tfarcenim** [comment]
What texture pack is that?
anyways, uploading a test build on github.

**Comment by SirAron111** [comment]
I am using the sphax texture pack PureBD craft pretty common pack but it’s not because of the texture pack it also shows up on having no texture pack. Disabling the symbols and numbers makes the texture go away like normal but the bar is overlapping will test the test build.

**Comment by SirAron111** [comment]
Seems to work in the new build 0.1.11a here are all the bars in that version to see.
![2019-04-07_03 02 50](https://user-images.githubusercontent.com/39855956/55677100-21892500-58e2-11e9-8cc7-ee5114c7f2f3.png)
![2019-04-07_03 02 53](https://user-images.githubusercontent.com/39855956/55677101-21892500-58e2-11e9-88cb-a3acb2624c7b.png)
![2019-04-07_03 02 56](https://user-images.githubusercontent.com/39855956/55677102-21892500-58e2-11e9-8354-8c4331a146a6.png)
![2019-04-07_03 03 34](https://user-images.githubusercontent.com/39855956/55677103-21892500-58e2-11e9-9001-62ffd3716151.png)
![2019-04-07_03 03 39](https://user-images.githubusercontent.com/39855956/55677104-21892500-58e2-11e9-941b-5d48620c774f.png)
![2019-04-07_03 04 12](https://user-images.githubusercontent.com/39855956/55677105-2221bb80-58e2-11e9-93e2-82e47f067d2c.png)
![2019-04-07_03 04 15](https://user-images.githubusercontent.com/39855956/55677106-2221bb80-58e2-11e9-9243-7a99bc9693b9.png)
![2019-04-07_03 04 39](https://user-images.githubusercontent.com/39855956/55677107-2221bb80-58e2-11e9-825d-463764d3bd22.png)

**Comment by SirAron111** [comment]
Well found a simple trick to fix the botania wing bar (simply set in the config of botania the wing bar height of 49/59 to 59/69) first number is without breath bar second is with breath bar.
There is an option for that you should make that as a little disclaimer or have your mod auto set the bar to these values so it’s not overlapping.
With this last thing done I think you can close this issue. Loving the mod great work
