### ISSUE TITLE
1.20.1 cannot show all bars other than health

### ISSUE THREAD

**Issue by Stupidplays** [Tfarcenim/ClassicBar#128]
![image](https://github.com/Tfarcenim/ClassicBar/assets/110560508/7c30bd0f-493f-4d39-be25-10ab02c8176f)

Mod version: classicbar-1.20.1-3.jar

**Comment by Frazack333** [comment]
hello, having the same issue to this day, have you fixed it? if not, can you share your mod list? we might be able to find an incompatibility

**Comment by TheOneHeadMan** [comment]
Revert back to previous version (1.20.1-2), fixed it for me.

**Comment by mcdodge34** [comment]
Got the same issue, I was sure it was a mod conflict and tried to troubleshoot it, but now solved with the previous version 1.20.1-2 subscribed to this to see if this gonna be fixed eventually.

**Comment by NovaLynxie** [comment]
I am surprised this issue is still ongoing. Rolling back to 1.20.1-2 did not fix this issue for me; rather, it got even worse. Now my game refuses even to load at all. Please, devs _fix this issue_ as it is either unplayable due to bug crashes or causing excessive log spam and missing bars.

**Comment by ifficles** [comment]
I, as well, had the same issue.  Had to roll back to the 1.20.1 1.1 version to have both bars displayed

**Comment by Tfarcenim** [comment]
Update to 1.20.1-4
